[tool.poetry]
name = "youtube-dl-nas"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
gevent = "^20.9.0"
gevent-websocket = "^0.10.1"
bottle = "^0.12.19"
youtube_dl = "^2020.12.14"
APScheduler = "^3.6.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
